### ISSUE TITLE
Can't get `markers_path` to work

### ISSUE THREAD

**Issue by ascandella** [paroxayte/autocd.vim#1]
I just installed your plugin (been looking for something exactly like this, thanks!). I've got `markers_filetype` to work how I expect it. However, I'd also like the plugin to set the current directory if I ever open a file whose parent directory contains a `.git` folder (e.g. is a git repo).

I've tried various permutations of setting `g:autocd#markers_path` but it doesn't seem to be working. Example:

```
cat ~/.vim/init/autocd.vim
let g:autocd#autocmd_enable = 1

let g:autocd#markers_filetype = {
      \ 'python': ['requirements.txt', 'setup.py'],
      \ 'rust': ['Cargo.toml'],
      \ }

let g:autocd#markers_path = {
      \ '/home/aiden': ['.git'],
      \ 'home/aiden/src': ['.git'],
      \ }
```

```
vim /home/aiden/src/bspwm/src/stack.c
```

Then call `:pwd` and it returns `/home/aiden`

```
ls -f /home/aiden/src/bspwm/.git
.   branches  info         refs     packed-refs  config  index
..  hooks     description  objects  logs         HEAD
```

However, if I open a rust project (with a `Cargo.toml`) file, it works fine.

I tried reading through the plugin source but don't know how to debug vim script. I'm guessing the sub-path detection isn't working properly, or I'm setting the configuration variable wrong.

What do you think?

**Comment by fireflowerr** [comment]
By any chance is your cursor on the NERDTree window? The autocmd triggers on BufEnter, where the buffer is not a NERDTree buffer. If you are currently on a NERDTree window the command will not trigger until you switch to the stack.c window. I can add exclusion to unlisted buffers and maybe a configuration to exclude buffers by regex match to prevent unnecessary switching. Let me know if the problem persists. I tested on my machine with '.git' as a marker for the /home/username key and it worked as expected.

**Comment by ascandella** [comment]
I don’t use nerd tree / have it installed, so no

**Comment by fireflowerr** [comment]
I found the bug, the command doesn't run on initial vim enter. I will push a fix in the next few minutes.

**Comment by fireflowerr** [comment]
I have pushed a fix, if the problem persists please report back. Thank you for your help and time.

**Comment by ascandella** [comment]
It's still not working for me. Can you show me how you set your `g:autocd#markers_path` to make .git work for you?

**Comment by ascandella** [comment]
Here is a screen recording. My main way of switching files is with FZF's `:History` and `:Files`, so as shown it's not just an issue with `VimEnter`. Inside my `test` directory in the recording, there's a fake python project and a fake git project. You can see the python project triggers the directory setting properly, but the git project does not:

![simplescreenrecorder-2019-01-28_11 07 17](https://user-images.githubusercontent.com/97087/51859988-575fcb00-22ed-11e9-8607-a58074c7471a.gif)

**Comment by fireflowerr** [comment]
I have created a debugging branch which outputs information about the search as it progresses. If you could use the plugin from the debugging branch, run `:Autocd` and paste the output it would be a great help. I replicated your test configuration and had no problems.

**Comment by ascandella** [comment]
Here's what I get when I `:e git-project/project-file.txt` the example from above:

```
Reported ft search result: 1
Reported dir key result: /home/aiden
Reported dir search result: 1
Reported target_dir: 1
```

**Comment by ascandella** [comment]
I think I found the issue -- `glob()` is returning an empty string for the `.git` directory, even though it exists.

```
echom "Globbing: " . glob('/home/aiden/src/test/git-project/.git')
```

prints:

```
Globbing: 
```

But:

```
:!ls /home/aiden/src/test/git-project/.git
branches
config
description
HEAD
hooks
info
objects
refs
```

Does glob properly return a non-empty string for you?

**Comment by ascandella** [comment]
I think it's because I have `.git` in my `set wildignore`: https://vi.stackexchange.com/questions/15457/what-does-wildignore-actually-do-and-what-functions-tools-respect-it

So I can remove that, but then e.g. `:Files` will try to descend into project files, which I don't want.

According to `:help glob`, if we pass a TRUE to the second argument of `glob()`, vim will ignore `wildignore` and `suffixes` for this call. What do you think?
